apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:/gyLIoQa4dY+aZHxrOlgPtCUlPzUlKmlBS23OM4xcANypymGc9IFiA==,iv:Aejwlp3toW8aenVMGSSJwWETvbE9swI3MNAlyVYKNNI=,tag:WfgUu/gg7un9ZOmop7gGYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vj2ypnjharckk5722wkgd9td4ejkm86wswa7pl6nqrvqwl2rh4gqf5n2p7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBemNrWFd4aFVoTHdVWk13
            RFhhMGYrZnlwWHo4Uk03alZKWExPQlc0NFhVCkhTYXpvdWV4YkNGUHJsVHY5cVRZ
            dDJGazQzN0hJeDVrUnVHUkMwQXd6emMKLS0tIGM3cU1qWlVIdjJtbkNFYU9RNmt6
            Y0pQTW5OUThpZndhdUZjTXRLbWxkLzQKJ1vneFcfCsk8rAKq8wucScgNvVf7NHeF
            sHHnh2E5hAPwsXfnscSzIg2hXIt16Wyy9GmlsKtCVfedBDbYVZEf8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T12:35:36Z"
    mac: ENC[AES256_GCM,data:ol+dpOcP83t2gyy1IyqG6keUjsrCiDhBa4NmMJtX1aT9ddpBFM2Nvd9C1R8/26GEZsnxDK1qyCvyvKwJFzRC2omeU/QzbKJCijbkJfJvuvmVbAs183FOpovEDPSixXAdu/IR3FNuxdVVKOxmyKnco0psu/o0lNLdwBobJOTNjkQ=,iv:yaaDqGU2Xrj8WdexBE2VBtBpjv9++O1TdFwTf5kzbAY=,tag:y8DPYKGFWN7TZriawIcwGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
